# Preview image Frame
PREVIEW_ROWS: 4
PREVIEW_COLS: 7
PREVIEW_MARGIN: 4
SAVE_FREQ: 20

# Size vector to generate images from
NOISE_SIZE: 100

# Configuration
EPOCHS: 1000
BATCH_SIZE: 32
GENERATE_RES: 3
IMAGE_SIZE: 128 # rows/cols
IMAGE_CHANNELS: 3

# Directory
IMAGE_DIR: '../dataset/cubism/'